# Problem 1 

In [41]:
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array= np.array([32, 45, 67, 89, 12]) 
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))
print(array)


ModuleNotFoundError: No module named 'numpy'

# Problem 2

In [ ]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.arrange(5,15,3)
print(sayilar2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3 = np.arrange(50,100,5,)
print(sayilar3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4 = np.zeros(10)
print(sayilar4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5 = np.ones(10)
print(sayilar5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6 = np.linspace(0,100,5)
print(sayilar6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_numbers = np.random.randint(10,31, size=5)
print(random_numbers)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random_numbers2 = np.random.uniform(-1, 1, size=10) 
print(random_numbers2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3 = np.random.randint(10, 50, size=(3,5))
print(random_numbers3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers.sum(axis=0))
print(random_numbers3.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random_numbers3.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random_numbers4 = np.random.randint(10, 20, size=8)
print(random_numbers4[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_numbers3[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_numbers3[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(random_numbers3**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5 = np.random.randint(-50, 50, size=(3,5))
print((random_numbers5 > 0 ) & (random_numbers5 % 2 == 0))


'''
[1 1 1 1 1]
[2 2 20 2 2]
[3 3 3 3]
'''

NameError: name 'np' is not defined